// <auto-generated />
using System;
using Forge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Forge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForgeDbContext))]
    partial class ForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Forge.Domain.ColdChain.TemperatureZone", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowableRange")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("StoredQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("temperature_zones", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Colonies.Colony", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("demand_profile");

                    b.HasKey("Id");

                    b.ToTable("colonies", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Colonies.ColonyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Colony")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DeliveryWindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeliveryWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lines")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lines");

                    b.HasKey("Id");

                    b.ToTable("colony_orders", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Docks.DockBay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("schedule");

                    b.HasKey("Id");

                    b.ToTable("dock_bays", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Docks.PickFace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Zone")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("pick_faces", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Gels.GelLot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedZoneId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AtRisk")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FefoPriority")
                        .HasColumnType("integer");

                    b.Property<Guid>("GelTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ProducedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("_history")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("temperature_history");

                    b.HasKey("Id");

                    b.HasIndex("GelTypeId", "ExpiresAt");

                    b.ToTable("gel_lots", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Gels.GelType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Formulation")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("Velocity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("gel_types", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Labor.Worker", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Shifts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("shifts");

                    b.HasKey("Id");

                    b.ToTable("workers", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Tasks.WarehouseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedWorker")
                        .HasColumnType("uuid");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("destination");

                    b.Property<TimeSpan>("EstimatedDuration")
                        .HasColumnType("interval");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("origin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TravelTime")
                        .HasColumnType("interval");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("warehouse_tasks", (string)null);
                });

            modelBuilder.Entity("Forge.Domain.Vessels.Starship", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CargoCapacity")
                        .HasColumnType("integer");

                    b.Property<Guid>("Destination")
                        .HasColumnType("uuid");

                    b.Property<int>("LoadedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("_windows")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("loading_windows");

                    b.HasKey("Id");

                    b.ToTable("starships", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
